---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      changed_when: false

    - name: Install cron.
      apt: name=git state=present

  roles:
    - role: alphanodes.git_rollout
